webtalk_init -webtalk_dir C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab4/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/CMP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 12 14:33:48 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c09a754e-6a60-4fa0-87f1-35e9d9931b20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8f1aba1a64c14d43b35e5ff25e6b9d81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1002 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2672973161 -regid "" -xml C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab4/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/CMP_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab4/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/CMP_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab4/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/CMP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
