# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/labo2.xdc

# Block Designs: bd/MUX_4B/MUX_4B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B || ORIG_REF_NAME==MUX_4B} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_ATAD_SPLIT_4_0_0/MUX_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_ATAD_SPLIT_4_1_0/MUX_4B_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_inv_0_0/MUX_4B_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_inv_0_0 || ORIG_REF_NAME==MUX_4B_xup_inv_0_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_0_0/MUX_4B_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_0_0 || ORIG_REF_NAME==MUX_4B_xup_and2_0_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_1_0/MUX_4B_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_1_0 || ORIG_REF_NAME==MUX_4B_xup_and2_1_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_2_0/MUX_4B_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_2_0 || ORIG_REF_NAME==MUX_4B_xup_and2_2_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_3_0/MUX_4B_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_3_0 || ORIG_REF_NAME==MUX_4B_xup_and2_3_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_4_0/MUX_4B_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_4_0 || ORIG_REF_NAME==MUX_4B_xup_and2_4_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_5_0/MUX_4B_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_5_0 || ORIG_REF_NAME==MUX_4B_xup_and2_5_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_6_0/MUX_4B_xup_and2_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_6_0 || ORIG_REF_NAME==MUX_4B_xup_and2_6_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_and2_7_0/MUX_4B_xup_and2_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_7_0 || ORIG_REF_NAME==MUX_4B_xup_and2_7_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_or2_0_0/MUX_4B_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_0_0 || ORIG_REF_NAME==MUX_4B_xup_or2_0_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_or2_1_0/MUX_4B_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_1_0 || ORIG_REF_NAME==MUX_4B_xup_or2_1_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_or2_2_0/MUX_4B_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_2_0 || ORIG_REF_NAME==MUX_4B_xup_or2_2_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xup_or2_3_0/MUX_4B_xup_or2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_3_0 || ORIG_REF_NAME==MUX_4B_xup_or2_3_0} -quiet] -quiet

# IP: bd/MUX_4B/ip/MUX_4B_xlconcat_0_1/MUX_4B_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xlconcat_0_1 || ORIG_REF_NAME==MUX_4B_xlconcat_0_1} -quiet] -quiet

# Block Designs: bd/CMP_4B/CMP_4B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B || ORIG_REF_NAME==CMP_4B} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_ATAD_SPLIT_4_0_0/CMP_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_ATAD_SPLIT_4_1_0/CMP_4B_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_xlconcat_0_0/CMP_4B_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xlconcat_0_0 || ORIG_REF_NAME==CMP_4B_xlconcat_0_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_xup_xnor2_0_0/CMP_4B_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_0_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_0_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_xup_xnor2_1_0/CMP_4B_xup_xnor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_1_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_1_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_xup_xnor2_2_0/CMP_4B_xup_xnor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_2_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_2_0} -quiet] -quiet

# IP: bd/CMP_4B/ip/CMP_4B_xup_xnor2_3_0/CMP_4B_xup_xnor2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_3_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_3_0} -quiet] -quiet

# Block Designs: bd/DIV_4_4B/DIV_4_4B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_4B || ORIG_REF_NAME==DIV_4_4B} -quiet] -quiet

# IP: bd/DIV_4_4B/ip/DIV_4_4B_ATAD_SPLIT_4_0_0/DIV_4_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==DIV_4_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/DIV_4_4B/ip/DIV_4_4B_xup_xor2_0_0/DIV_4_4B_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_4B_xup_xor2_0_0 || ORIG_REF_NAME==DIV_4_4B_xup_xor2_0_0} -quiet] -quiet

# IP: bd/DIV_4_4B/ip/DIV_4_4B_xlconcat_0_1/DIV_4_4B_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_4B_xlconcat_0_1 || ORIG_REF_NAME==DIV_4_4B_xlconcat_0_1} -quiet] -quiet

# Block Designs: bd/UAL/UAL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UAL || ORIG_REF_NAME==UAL} -quiet] -quiet

# IP: bd/UAL/ip/UAL_MUX_4B_0_0/UAL_MUX_4B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UAL_MUX_4B_0_0 || ORIG_REF_NAME==UAL_MUX_4B_0_0} -quiet] -quiet

# IP: bd/UAL/ip/UAL_DIV_4_4B_0_0/UAL_DIV_4_4B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UAL_DIV_4_4B_0_0 || ORIG_REF_NAME==UAL_DIV_4_4B_0_0} -quiet] -quiet

# IP: bd/UAL/ip/UAL_CMP_4B_0_0/UAL_CMP_4B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UAL_CMP_4B_0_0 || ORIG_REF_NAME==UAL_CMP_4B_0_0} -quiet] -quiet

# XDC: bd/MUX_4B/MUX_4B_ooc.xdc

# XDC: bd/CMP_4B/CMP_4B_ooc.xdc

# XDC: bd/DIV_4_4B/DIV_4_4B_ooc.xdc

# XDC: bd/UAL/UAL_ooc.xdc
