@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Sep 24 19:08:39 -0400 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim fullAdder4B_wrapper_behav -key {Behavioral:sim_1:Functional:fullAdder4B_wrapper} -tclbatch fullAdder4B_wrapper.tcl -protoinst "protoinst_files/fullAdder4B.protoinst" -protoinst "protoinst_files/fullAdder1B.protoinst" -view C:/Users/Adam/Downloads/INF1500/lab1/fullAdder1B_wrapper_behav.wcfg -log simulate.log"
call xsim  fullAdder4B_wrapper_behav -key {Behavioral:sim_1:Functional:fullAdder4B_wrapper} -tclbatch fullAdder4B_wrapper.tcl -protoinst "protoinst_files/fullAdder4B.protoinst" -protoinst "protoinst_files/fullAdder1B.protoinst" -view C:/Users/Adam/Downloads/INF1500/lab1/fullAdder1B_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
