# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/UAL_CMP_4B_0_0.xci
# IP: The module: 'UAL_CMP_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_3_0/CMP_4B_xup_xnor2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_3_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_2_0/CMP_4B_xup_xnor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_2_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_1_0/CMP_4B_xup_xnor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_1_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_0_0/CMP_4B_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_0_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xlconcat_0_0/CMP_4B_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xlconcat_0_0 || ORIG_REF_NAME==CMP_4B_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ATAD_SPLIT_4_1_0/CMP_4B_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ATAD_SPLIT_4_0_0/CMP_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UAL_CMP_4B_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/UAL_CMP_4B_0_0.xci
# IP: The module: 'UAL_CMP_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_3_0/CMP_4B_xup_xnor2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_3_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_2_0/CMP_4B_xup_xnor2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_2_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_1_0/CMP_4B_xup_xnor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_1_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xup_xnor2_0_0/CMP_4B_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xup_xnor2_0_0 || ORIG_REF_NAME==CMP_4B_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_xlconcat_0_0/CMP_4B_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_xlconcat_0_0 || ORIG_REF_NAME==CMP_4B_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ATAD_SPLIT_4_1_0/CMP_4B_ATAD_SPLIT_4_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ATAD_SPLIT_4_0_0/CMP_4B_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CMP_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_CMP_4B_0_0/src/CMP_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UAL_CMP_4B_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
