# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/MUX3_1_MUX_INDEX_3_0.xci
# IP: The module: 'MUX3_1_MUX_INDEX_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ATAD_SPLIT_2_0_0/MUX_INDEX_ATAD_SPLIT_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0 || ORIG_REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_inv_0_0/MUX_INDEX_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_inv_1_0/MUX_INDEX_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_0_0/MUX_INDEX_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_1_0/MUX_INDEX_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_2_0/MUX_INDEX_xup_and3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_2_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_or3_0_0/MUX_INDEX_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_or3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_or3_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MUX3_1_MUX_INDEX_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/MUX3_1_MUX_INDEX_3_0.xci
# IP: The module: 'MUX3_1_MUX_INDEX_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ATAD_SPLIT_2_0_0/MUX_INDEX_ATAD_SPLIT_2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0 || ORIG_REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_inv_0_0/MUX_INDEX_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_inv_1_0/MUX_INDEX_xup_inv_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_0_0/MUX_INDEX_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_1_0/MUX_INDEX_xup_and3_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_and3_2_0/MUX_INDEX_xup_and3_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_2_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_xup_or3_0_0/MUX_INDEX_xup_or3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_or3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_or3_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MUX3_1_MUX_INDEX_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
