# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/labo3.xdc

# Block Designs: bd/MUX_INDEX/MUX_INDEX.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX || ORIG_REF_NAME==MUX_INDEX} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_ATAD_SPLIT_2_0_0/MUX_INDEX_ATAD_SPLIT_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0 || ORIG_REF_NAME==MUX_INDEX_ATAD_SPLIT_2_0_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_inv_0_0/MUX_INDEX_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_0_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_inv_1_0/MUX_INDEX_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_inv_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_inv_1_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_and3_0_0/MUX_INDEX_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_0_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_and3_1_0/MUX_INDEX_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_1_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_1_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_and3_2_0/MUX_INDEX_xup_and3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_and3_2_0 || ORIG_REF_NAME==MUX_INDEX_xup_and3_2_0} -quiet] -quiet

# IP: bd/MUX_INDEX/ip/MUX_INDEX_xup_or3_0_0/MUX_INDEX_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_INDEX_xup_or3_0_0 || ORIG_REF_NAME==MUX_INDEX_xup_or3_0_0} -quiet] -quiet

# Block Designs: bd/MUX3_1/MUX3_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1 || ORIG_REF_NAME==MUX3_1} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_ATAD_SPLIT_4_0_0/MUX3_1_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX3_1_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_ATAD_SPLIT_4_1_0/MUX3_1_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX3_1_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_ATAD_SPLIT_4_2_0/MUX3_1_ATAD_SPLIT_4_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_ATAD_SPLIT_4_2_0 || ORIG_REF_NAME==MUX3_1_ATAD_SPLIT_4_2_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_xlconcat_0_0/MUX3_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_xlconcat_0_0 || ORIG_REF_NAME==MUX3_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_MUX_INDEX_1_0/MUX3_1_MUX_INDEX_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_MUX_INDEX_1_0 || ORIG_REF_NAME==MUX3_1_MUX_INDEX_1_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_MUX_INDEX_2_0/MUX3_1_MUX_INDEX_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_MUX_INDEX_2_0 || ORIG_REF_NAME==MUX3_1_MUX_INDEX_2_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/MUX3_1_MUX_INDEX_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_MUX_INDEX_3_0 || ORIG_REF_NAME==MUX3_1_MUX_INDEX_3_0} -quiet] -quiet

# IP: bd/MUX3_1/ip/MUX3_1_MUX_INDEX_0_0/MUX3_1_MUX_INDEX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX3_1_MUX_INDEX_0_0 || ORIG_REF_NAME==MUX3_1_MUX_INDEX_0_0} -quiet] -quiet

# Block Designs: bd/LAB3_SYS/LAB3_SYS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LAB3_SYS || ORIG_REF_NAME==LAB3_SYS} -quiet] -quiet

# IP: bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/LAB3_SYS_BIN_GRAY_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LAB3_SYS_BIN_GRAY_0_1 || ORIG_REF_NAME==LAB3_SYS_BIN_GRAY_0_1} -quiet] -quiet

# IP: bd/LAB3_SYS/ip/LAB3_SYS_DIV_4_REST_0_1/LAB3_SYS_DIV_4_REST_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LAB3_SYS_DIV_4_REST_0_1 || ORIG_REF_NAME==LAB3_SYS_DIV_4_REST_0_1} -quiet] -quiet

# IP: bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/LAB3_SYS_CRYPTO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LAB3_SYS_CRYPTO_0_1 || ORIG_REF_NAME==LAB3_SYS_CRYPTO_0_1} -quiet] -quiet

# IP: bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/LAB3_SYS_MUX3_1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LAB3_SYS_MUX3_1_0_1 || ORIG_REF_NAME==LAB3_SYS_MUX3_1_0_1} -quiet] -quiet

# Block Designs: bd/DIV_4_REST/DIV_4_REST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_REST || ORIG_REF_NAME==DIV_4_REST} -quiet] -quiet

# IP: bd/DIV_4_REST/ip/DIV_4_REST_ATAD_SPLIT_4_0_0/DIV_4_REST_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_REST_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==DIV_4_REST_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/DIV_4_REST/ip/DIV_4_REST_xlconcat_0_0/DIV_4_REST_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIV_4_REST_xlconcat_0_0 || ORIG_REF_NAME==DIV_4_REST_xlconcat_0_0} -quiet] -quiet

# Block Designs: bd/CRYPTO/CRYPTO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO || ORIG_REF_NAME==CRYPTO} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_ATAD_SPLIT_4_0_0/CRYPTO_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xlconcat_0_0/CRYPTO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xlconcat_0_0 || ORIG_REF_NAME==CRYPTO_xlconcat_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or2_0_0/CRYPTO_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_0_0 || ORIG_REF_NAME==CRYPTO_xup_or2_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and2_0_0/CRYPTO_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_0_0 || ORIG_REF_NAME==CRYPTO_xup_and2_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and3_0_0/CRYPTO_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and3_0_0 || ORIG_REF_NAME==CRYPTO_xup_and3_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_inv_0_0/CRYPTO_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_0_0 || ORIG_REF_NAME==CRYPTO_xup_inv_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_inv_1_0/CRYPTO_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_1_0 || ORIG_REF_NAME==CRYPTO_xup_inv_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_inv_2_0/CRYPTO_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_2_0 || ORIG_REF_NAME==CRYPTO_xup_inv_2_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_inv_3_0/CRYPTO_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_3_0 || ORIG_REF_NAME==CRYPTO_xup_inv_3_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and4_3_0/CRYPTO_xup_and4_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_3_0 || ORIG_REF_NAME==CRYPTO_xup_and4_3_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and2_1_0/CRYPTO_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_1_0 || ORIG_REF_NAME==CRYPTO_xup_and2_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or2_2_0/CRYPTO_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_2_0 || ORIG_REF_NAME==CRYPTO_xup_or2_2_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and4_8_0/CRYPTO_xup_and4_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_8_0 || ORIG_REF_NAME==CRYPTO_xup_and4_8_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or3_0_0/CRYPTO_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_0_0 || ORIG_REF_NAME==CRYPTO_xup_or3_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or3_1_0/CRYPTO_xup_or3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_1_0 || ORIG_REF_NAME==CRYPTO_xup_or3_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or3_2_0/CRYPTO_xup_or3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_2_0 || ORIG_REF_NAME==CRYPTO_xup_or3_2_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or3_3_0/CRYPTO_xup_or3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_3_0 || ORIG_REF_NAME==CRYPTO_xup_or3_3_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_xor2_0_0/CRYPTO_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_xor2_1_0/CRYPTO_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_xnor2_0_0/CRYPTO_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_0_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_xnor2_1_0/CRYPTO_xup_xnor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_or2_1_0/CRYPTO_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_1_0 || ORIG_REF_NAME==CRYPTO_xup_or2_1_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and2_2_0/CRYPTO_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_2_0 || ORIG_REF_NAME==CRYPTO_xup_and2_2_0} -quiet] -quiet

# IP: bd/CRYPTO/ip/CRYPTO_xup_and2_3_0/CRYPTO_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_3_0 || ORIG_REF_NAME==CRYPTO_xup_and2_3_0} -quiet] -quiet

# Block Designs: bd/BIN_GRAY/BIN_GRAY.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY || ORIG_REF_NAME==BIN_GRAY} -quiet] -quiet

# IP: bd/BIN_GRAY/ip/BIN_GRAY_ATAD_SPLIT_4_0_0/BIN_GRAY_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/BIN_GRAY/ip/BIN_GRAY_xup_xor2_0_0/BIN_GRAY_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_0_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_0_0} -quiet] -quiet

# IP: bd/BIN_GRAY/ip/BIN_GRAY_xup_xor2_1_0/BIN_GRAY_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_1_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_1_0} -quiet] -quiet

# IP: bd/BIN_GRAY/ip/BIN_GRAY_xup_xor2_2_0/BIN_GRAY_xup_xor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_2_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_2_0} -quiet] -quiet

# IP: bd/BIN_GRAY/ip/BIN_GRAY_xlconcat_0_0/BIN_GRAY_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xlconcat_0_0 || ORIG_REF_NAME==BIN_GRAY_xlconcat_0_0} -quiet] -quiet

# XDC: bd/MUX_INDEX/MUX_INDEX_ooc.xdc

# XDC: bd/MUX3_1/MUX3_1_ooc.xdc

# XDC: bd/LAB3_SYS/LAB3_SYS_ooc.xdc

# XDC: bd/DIV_4_REST/DIV_4_REST_ooc.xdc

# XDC: bd/CRYPTO/CRYPTO_ooc.xdc

# XDC: bd/BIN_GRAY/BIN_GRAY_ooc.xdc
