# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.runs/synth_1/LAB3_SYS_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {DRC INBB-3}  -string {{ERROR: [DRC INBB-3] Black Box Instances: Cell 'LAB3_SYS_i/BIN_GRAY_0/U0/xlconcat_0' of type 'LAB3_SYS_BIN_GRAY_0_1__BIN_GRAY_xlconcat_0_0' has undefined contents and is considered a black box.  The contents of this cell must be defined for opt_design to complete successfully.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.cache/wt [current_project]
set_property parent.project_path C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Users/Adam/Downloads/INF1500/ip_repo/MUX3_1
  c:/Users/Adam/Downloads/INF1500/ip_repo/BIN_GRAY
  c:/Users/Adam/Downloads/INF1500/ip_repo/MUX_INDEX
  c:/Users/Adam/Downloads/INF1500/ip_repo/CRYPTO
  c:/Users/Adam/Downloads/INF1500/ip_repo/DIV_4_REST
  c:/Users/Adam/Downloads/INF1500/ip_repo/ATAD_LIB
  c:/Users/Adam/Downloads/INF1500/ip_repo/XUP_LIB
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/DIV_4_REST/hdl/DIV_4_REST_wrapper.vhd
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/CRYPTO/hdl/CRYPTO_wrapper.vhd
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/BIN_GRAY/hdl/BIN_GRAY_wrapper.vhd
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX_INDEX/hdl/MUX_INDEX_wrapper.vhd
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/hdl/MUX3_1_wrapper.vhd
  C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/hdl/LAB3_SYS_wrapper.vhd
}
add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX_INDEX/MUX_INDEX.bd
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX_INDEX/MUX_INDEX_ooc.xdc]

add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/MUX3_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_1_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_2_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/ip/MUX3_1_MUX_INDEX_0_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/MUX3_1/MUX3_1_ooc.xdc]

add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/LAB3_SYS.bd
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_DIV_4_REST_0_1/src/DIV_4_REST_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/src/MUX3_1_MUX_INDEX_1_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/src/MUX3_1_MUX_INDEX_2_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/src/MUX3_1_MUX_INDEX_3_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/src/MUX3_1_MUX_INDEX_0_0/src/MUX_INDEX_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_MUX3_1_0_1/src/MUX3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/LAB3_SYS_ooc.xdc]

add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/DIV_4_REST/DIV_4_REST.bd
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/DIV_4_REST/DIV_4_REST_ooc.xdc]

add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/CRYPTO/CRYPTO.bd
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/CRYPTO/CRYPTO_ooc.xdc]

add_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/BIN_GRAY/BIN_GRAY.bd
set_property used_in_implementation false [get_files -all C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/BIN_GRAY/BIN_GRAY_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/labo3.xdc
set_property used_in_implementation false [get_files C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/labo3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top LAB3_SYS_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LAB3_SYS_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LAB3_SYS_wrapper_utilization_synth.rpt -pb LAB3_SYS_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
