# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/LAB3_SYS_CRYPTO_0_1.xci
# IP: The module: 'LAB3_SYS_CRYPTO_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_ATAD_SPLIT_4_0_0/CRYPTO_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xlconcat_0_0/CRYPTO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xlconcat_0_0 || ORIG_REF_NAME==CRYPTO_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_0_0/CRYPTO_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_0_0 || ORIG_REF_NAME==CRYPTO_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_0_0/CRYPTO_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_0_0 || ORIG_REF_NAME==CRYPTO_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and3_0_0/CRYPTO_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and3_0_0 || ORIG_REF_NAME==CRYPTO_xup_and3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_0_0/CRYPTO_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_0_0 || ORIG_REF_NAME==CRYPTO_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_1_0/CRYPTO_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_1_0 || ORIG_REF_NAME==CRYPTO_xup_inv_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_2_0/CRYPTO_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_2_0 || ORIG_REF_NAME==CRYPTO_xup_inv_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_3_0/CRYPTO_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_3_0 || ORIG_REF_NAME==CRYPTO_xup_inv_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and4_3_0/CRYPTO_xup_and4_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_3_0 || ORIG_REF_NAME==CRYPTO_xup_and4_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_1_0/CRYPTO_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_1_0 || ORIG_REF_NAME==CRYPTO_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_2_0/CRYPTO_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_2_0 || ORIG_REF_NAME==CRYPTO_xup_or2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and4_8_0/CRYPTO_xup_and4_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_8_0 || ORIG_REF_NAME==CRYPTO_xup_and4_8_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_0_0/CRYPTO_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_0_0 || ORIG_REF_NAME==CRYPTO_xup_or3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_1_0/CRYPTO_xup_or3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_1_0 || ORIG_REF_NAME==CRYPTO_xup_or3_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_2_0/CRYPTO_xup_or3_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_2_0 || ORIG_REF_NAME==CRYPTO_xup_or3_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_3_0/CRYPTO_xup_or3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_3_0 || ORIG_REF_NAME==CRYPTO_xup_or3_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xor2_0_0/CRYPTO_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xor2_1_0/CRYPTO_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xnor2_0_0/CRYPTO_xup_xnor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xnor2_1_0/CRYPTO_xup_xnor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_1_0/CRYPTO_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_1_0 || ORIG_REF_NAME==CRYPTO_xup_or2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_2_0/CRYPTO_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_2_0 || ORIG_REF_NAME==CRYPTO_xup_and2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_3_0/CRYPTO_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_3_0 || ORIG_REF_NAME==CRYPTO_xup_and2_3_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_SYS_CRYPTO_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/LAB3_SYS_CRYPTO_0_1.xci
# IP: The module: 'LAB3_SYS_CRYPTO_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_ATAD_SPLIT_4_0_0/CRYPTO_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==CRYPTO_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xlconcat_0_0/CRYPTO_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xlconcat_0_0 || ORIG_REF_NAME==CRYPTO_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_0_0/CRYPTO_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_0_0 || ORIG_REF_NAME==CRYPTO_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_0_0/CRYPTO_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_0_0 || ORIG_REF_NAME==CRYPTO_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and3_0_0/CRYPTO_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and3_0_0 || ORIG_REF_NAME==CRYPTO_xup_and3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_0_0/CRYPTO_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_0_0 || ORIG_REF_NAME==CRYPTO_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_1_0/CRYPTO_xup_inv_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_1_0 || ORIG_REF_NAME==CRYPTO_xup_inv_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_2_0/CRYPTO_xup_inv_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_2_0 || ORIG_REF_NAME==CRYPTO_xup_inv_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_inv_3_0/CRYPTO_xup_inv_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_inv_3_0 || ORIG_REF_NAME==CRYPTO_xup_inv_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and4_3_0/CRYPTO_xup_and4_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_3_0 || ORIG_REF_NAME==CRYPTO_xup_and4_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_1_0/CRYPTO_xup_and2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_1_0 || ORIG_REF_NAME==CRYPTO_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_2_0/CRYPTO_xup_or2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_2_0 || ORIG_REF_NAME==CRYPTO_xup_or2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and4_8_0/CRYPTO_xup_and4_8_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and4_8_0 || ORIG_REF_NAME==CRYPTO_xup_and4_8_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_0_0/CRYPTO_xup_or3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_0_0 || ORIG_REF_NAME==CRYPTO_xup_or3_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_1_0/CRYPTO_xup_or3_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_1_0 || ORIG_REF_NAME==CRYPTO_xup_or3_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_2_0/CRYPTO_xup_or3_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_2_0 || ORIG_REF_NAME==CRYPTO_xup_or3_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or3_3_0/CRYPTO_xup_or3_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or3_3_0 || ORIG_REF_NAME==CRYPTO_xup_or3_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xor2_0_0/CRYPTO_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xor2_1_0/CRYPTO_xup_xor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xnor2_0_0/CRYPTO_xup_xnor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_0_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_xnor2_1_0/CRYPTO_xup_xnor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_xnor2_1_0 || ORIG_REF_NAME==CRYPTO_xup_xnor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_or2_1_0/CRYPTO_xup_or2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_or2_1_0 || ORIG_REF_NAME==CRYPTO_xup_or2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_2_0/CRYPTO_xup_and2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_2_0 || ORIG_REF_NAME==CRYPTO_xup_and2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_xup_and2_3_0/CRYPTO_xup_and2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CRYPTO_xup_and2_3_0 || ORIG_REF_NAME==CRYPTO_xup_and2_3_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_CRYPTO_0_1/src/CRYPTO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_SYS_CRYPTO_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
