# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/UAL_MUX_4B_0_0.xci
# IP: The module: 'UAL_MUX_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xlconcat_0_1/MUX_4B_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xlconcat_0_1 || ORIG_REF_NAME==MUX_4B_xlconcat_0_1} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_3_0/MUX_4B_xup_or2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_3_0 || ORIG_REF_NAME==MUX_4B_xup_or2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_2_0/MUX_4B_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_2_0 || ORIG_REF_NAME==MUX_4B_xup_or2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_1_0/MUX_4B_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_1_0 || ORIG_REF_NAME==MUX_4B_xup_or2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_0_0/MUX_4B_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_0_0 || ORIG_REF_NAME==MUX_4B_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_7_0/MUX_4B_xup_and2_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_7_0 || ORIG_REF_NAME==MUX_4B_xup_and2_7_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_6_0/MUX_4B_xup_and2_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_6_0 || ORIG_REF_NAME==MUX_4B_xup_and2_6_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_5_0/MUX_4B_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_5_0 || ORIG_REF_NAME==MUX_4B_xup_and2_5_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_4_0/MUX_4B_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_4_0 || ORIG_REF_NAME==MUX_4B_xup_and2_4_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_3_0/MUX_4B_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_3_0 || ORIG_REF_NAME==MUX_4B_xup_and2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_2_0/MUX_4B_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_2_0 || ORIG_REF_NAME==MUX_4B_xup_and2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_1_0/MUX_4B_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_1_0 || ORIG_REF_NAME==MUX_4B_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_0_0/MUX_4B_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_0_0 || ORIG_REF_NAME==MUX_4B_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_inv_0_0/MUX_4B_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_inv_0_0 || ORIG_REF_NAME==MUX_4B_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ATAD_SPLIT_4_1_0/MUX_4B_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ATAD_SPLIT_4_0_0/MUX_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UAL_MUX_4B_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/UAL_MUX_4B_0_0.xci
# IP: The module: 'UAL_MUX_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xlconcat_0_1/MUX_4B_xlconcat_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xlconcat_0_1 || ORIG_REF_NAME==MUX_4B_xlconcat_0_1} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_3_0/MUX_4B_xup_or2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_3_0 || ORIG_REF_NAME==MUX_4B_xup_or2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_2_0/MUX_4B_xup_or2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_2_0 || ORIG_REF_NAME==MUX_4B_xup_or2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_1_0/MUX_4B_xup_or2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_1_0 || ORIG_REF_NAME==MUX_4B_xup_or2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_or2_0_0/MUX_4B_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_or2_0_0 || ORIG_REF_NAME==MUX_4B_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_7_0/MUX_4B_xup_and2_7_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_7_0 || ORIG_REF_NAME==MUX_4B_xup_and2_7_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_6_0/MUX_4B_xup_and2_6_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_6_0 || ORIG_REF_NAME==MUX_4B_xup_and2_6_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_5_0/MUX_4B_xup_and2_5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_5_0 || ORIG_REF_NAME==MUX_4B_xup_and2_5_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_4_0/MUX_4B_xup_and2_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_4_0 || ORIG_REF_NAME==MUX_4B_xup_and2_4_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_3_0/MUX_4B_xup_and2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_3_0 || ORIG_REF_NAME==MUX_4B_xup_and2_3_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_2_0/MUX_4B_xup_and2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_2_0 || ORIG_REF_NAME==MUX_4B_xup_and2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_1_0/MUX_4B_xup_and2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_1_0 || ORIG_REF_NAME==MUX_4B_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_and2_0_0/MUX_4B_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_and2_0_0 || ORIG_REF_NAME==MUX_4B_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_xup_inv_0_0/MUX_4B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_xup_inv_0_0 || ORIG_REF_NAME==MUX_4B_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ATAD_SPLIT_4_1_0/MUX_4B_ATAD_SPLIT_4_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ATAD_SPLIT_4_0_0/MUX_4B_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab2/lab2/lab2.srcs/sources_1/bd/UAL/ip/UAL_MUX_4B_0_0/src/MUX_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UAL_MUX_4B_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
