# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Adam/Downloads/INF1500/labo1.xdc

# Block Designs: bd/fullAdder1B/fullAdder1B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B || ORIG_REF_NAME==fullAdder1B} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_0_0/fullAdder1B_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_0_0 || ORIG_REF_NAME==fullAdder1B_xup_and2_0_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_1_0/fullAdder1B_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_1_0 || ORIG_REF_NAME==fullAdder1B_xup_and2_1_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_2_0/fullAdder1B_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_2_0 || ORIG_REF_NAME==fullAdder1B_xup_and2_2_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_xor2_0_0/fullAdder1B_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_xor2_0_0 || ORIG_REF_NAME==fullAdder1B_xup_xor2_0_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_xor2_1_0/fullAdder1B_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_xor2_1_0 || ORIG_REF_NAME==fullAdder1B_xup_xor2_1_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_or3_0_0/fullAdder1B_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_or3_0_0 || ORIG_REF_NAME==fullAdder1B_xup_or3_0_0} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_0_2/fullAdder1B_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_0_2 || ORIG_REF_NAME==fullAdder1B_xup_and2_0_2} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_1_2/fullAdder1B_xup_and2_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_1_2 || ORIG_REF_NAME==fullAdder1B_xup_and2_1_2} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_and2_2_2/fullAdder1B_xup_and2_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_and2_2_2 || ORIG_REF_NAME==fullAdder1B_xup_and2_2_2} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_xor2_0_2/fullAdder1B_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_xor2_0_2 || ORIG_REF_NAME==fullAdder1B_xup_xor2_0_2} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_xor2_1_2/fullAdder1B_xup_xor2_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_xor2_1_2 || ORIG_REF_NAME==fullAdder1B_xup_xor2_1_2} -quiet] -quiet

# IP: bd/fullAdder1B/ip/fullAdder1B_xup_or3_0_2/fullAdder1B_xup_or3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fullAdder1B_xup_or3_0_2 || ORIG_REF_NAME==fullAdder1B_xup_or3_0_2} -quiet] -quiet

# XDC: bd/fullAdder1B/fullAdder1B_ooc.xdc
