# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/LAB3_SYS_BIN_GRAY_0_1.xci
# IP: The module: 'LAB3_SYS_BIN_GRAY_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_ATAD_SPLIT_4_0_0/BIN_GRAY_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_0_0/BIN_GRAY_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_0_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_1_0/BIN_GRAY_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_1_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_2_0/BIN_GRAY_xup_xor2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_2_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xlconcat_0_0/BIN_GRAY_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xlconcat_0_0 || ORIG_REF_NAME==BIN_GRAY_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_SYS_BIN_GRAY_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/LAB3_SYS_BIN_GRAY_0_1.xci
# IP: The module: 'LAB3_SYS_BIN_GRAY_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_ATAD_SPLIT_4_0_0/BIN_GRAY_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==BIN_GRAY_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_0_0/BIN_GRAY_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_0_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_1_0/BIN_GRAY_xup_xor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_1_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xup_xor2_2_0/BIN_GRAY_xup_xor2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xup_xor2_2_0 || ORIG_REF_NAME==BIN_GRAY_xup_xor2_2_0} -quiet] -quiet

# IP: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_xlconcat_0_0/BIN_GRAY_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BIN_GRAY_xlconcat_0_0 || ORIG_REF_NAME==BIN_GRAY_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/Adam/Downloads/INF1500/INF1500_2034584_2081643_Lab3/lab3/lab3.srcs/sources_1/bd/LAB3_SYS/ip/LAB3_SYS_BIN_GRAY_0_1/src/BIN_GRAY_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LAB3_SYS_BIN_GRAY_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
